### PR TITLE
Update centralmoment() to support MonteCarlo()

### LINKED ISSUE #28: centralmoment not working w/ MonteCarlo()
Numerically it doesn't make a ton of sense to solve the `centralmoment` problem with MonteCarlo() but it should work. Issue related to using `sol.u` vs `sol[:]` and the different solution type between MonteCarlo() and Koopman(). Related to #24

### PR DESCRIPTION
**Pull request by agerlach**
Closes #28 

Also added relevant tests.

### CODE REVIEW

**Comment by agerlach** [comment]
@ChrisRackauckas I have no idea why this test is failing. DiffEqSensitivity is in the TOML Extras and `using DiffEqSensitivity` is there. None of these tests or the TOML are touched by the commits and passed previously. Do you have any suggestions? Thanks.

**Comment by ChrisRackauckas** [comment]
https://travis-ci.org/github/SciML/DiffEqUncertainty.jl/jobs/721741699#L380

It's a versioning issue. Something is keeping it back in the stone age.

**Comment by agerlach** [comment]
Why would it work locally though? I thought running `Pkg> test` ensured the same environment

**Comment by agerlach** [comment]
hmmm... doing `up` on the dev environment knocked it back to the stoneage locally too

**Comment by agerlach** [comment]
@ChrisRackauckas Can you rerun this test? This PR was held up by the DataStructures@0.18 debacle.

**Comment by ChrisRackauckas** [comment]
I bumped the tolerances a bit to make the new AD tests pass but I think there's a real failure somewhere.

**Comment by sdwfrost** [comment]
What's the blocker on this? My toy example fails (although it fails on both MonteCarlo and Koopman https://gist.github.com/sdwfrost/2c14346ced4d8279ef1769d1ef81d78d

**Comment by ChrisRackauckas** [comment]
I think the main blocker is that we will need to change the repo substantially in order to really get the performance in check. It needs a DSL. Without it, it cannot do codegen in a way that's type stable. So that's a pretty big project that will startup in a bit here.

**Pull request closed without merging**
